/**
 * Created by hxsd on 2016/12/23.
 */
var myapp=angular.module("myapp",["ionic"]);
myapp.config(function($stateProvider,$urlRouterProvider){
    $stateProvider
        .state("tabs",{
            url:"/tabs",
            abstract:true,  // 抽象地，意思是不直接显示
            templateUrl:"templates/tabs/tabs.html",
            //controller:"tabsCtrl"
        })
        .state("tabs.news",{
            url:"/news",
            views:{"tab-news":{
                templateUrl:"templates/news/news.html",
                controller:"newsCtrl"
            }}
        })
        .state("tabs.newstext",{
            url:"/newstext?:title",
            views:{"tab-news":{
                templateUrl:"templates/newstext/newstext.html",
                controller:"newstextCtrl"
            }}
        })
        .state("tabs.novel",{
            url:"/novel",
            views:{"tab-novel":{
                templateUrl:"templates/novel/novel.html",
                controller:"novelCtrl"
            }}
        })
        .state("tabs.novelread",{
            url:"/novelread?:title",
            //url:"/novelread",
            views:{"tab-novel":{
                templateUrl:"templates/novelread/novelread.html",
                controller:"novelreadCtrl"
            }}
        })
        .state("tabs.novelreadnews",{
            url:"/novelreadnews?:title",
            //url:"/novelread",
            views:{"tab-novel":{
                templateUrl:"templates/novelreadnews/novelreadnews.html",
                controller:"novelreadnewsCtrl"
            }}
        })
        .state("tabs.novelreading",{
            url:"/novelreading?:title",
            //url:"/novelread",
            views:{"tab-novel":{
                templateUrl:"templates/novelreading/novelreading.html",
                controller:"novelreadingCtrl"
            }}
        })
        .state("tabs.novelreadfuture",{
            url:"/novelreadfuture?:title",
            //url:"/novelread",
            views:{"tab-novel":{
                templateUrl:"templates/novelreadfuture/novelreadfuture.html",
                controller:"novelreadfutureCtrl"
            }}
        })
        .state("tabs.novelclassic",{
            url:"/novelclassic?:title",
            //url:"/novelread",
            views:{"tab-novel":{
                templateUrl:"templates/novelclassic/novelclassic.html",
                controller:"novelclassicCtrl"
            }}
        })
        .state("tabs.mylogin",{
            url:"/mylogin",
            views:{"tab-mylogin":{
                templateUrl:"templates/mylogin/mylogin.html",
                //controller:"newsCtrl"
            }}
        })
        .state("tour",{
            url:"/tour",
            templateUrl:"templates/tour/tour.html"
        });
    $urlRouterProvider.otherwise("/tour")
})