/**
 * Created by Administrator on 2016/12/25.
 */
myapp.controller("novelreadCtrl", function ($scope,$stateParams) {
    $scope.novels = [
        {id:"1",title: "路人女主的养成方法 第11卷",
            imgcover:"images/novellun1t1.jpg",
            date:"2016-12-8 连载中",
            author:"丸户史明",
            type:"爱情/校园",
            click:"点击 1483648",
            Subscribe:"订阅  46972",
            txt:"「我会将你变成让人心动不止的女主角的！」这是讲述我，安芸伦也如何将一名不起眼的少女调教成合格的女主角，并以她为蓝本制作GALGAME的感动故事……",
            newchapter:"第十一卷 虎穴特典 诗羽追加剧情",
            allchapter:[{chapter:"第一卷"},
                {chapter:"第二卷"},
                {chapter:"第三卷"},
                {chapter:"第四卷"},
                {chapter:"第五卷"},
                {chapter:"第六卷"},
                {chapter:"第七卷"},
                {chapter:"第八卷"},
                {chapter:"第九卷"},
                {chapter:"第十卷"},
                {chapter:"第十一卷"}
            ],
            imgsrc: "images/novellun1.jpg"},
        {id:"2",title: "Campione！弑神者！ 第19卷",
            imgcover:"images/novellun2t1.jpg",
            date:"2016-12-4 连载中",
            author:"丈月城",
            type:"神鬼/后宫",
            click:"点击 9632261",
            Subscribe:"订阅  30873",
            txt:"弑神者得到神的权能，得到了那个力量的人被称呼为王『Campione』，并称为霸者、魔王。追求平静的每天的高中生草薙护堂，可是却被自称为护堂的爱人的魔术师艾丽卡所卷入荒神的邂逅之中！？",
            newchapter:"第十九卷 魔王内战 ",
            allchapter:[{chapter:"第一卷"},
                {chapter:"第二卷"},
                {chapter:"第三卷"},
                {chapter:"第四卷"},
                {chapter:"第五卷"},
                {chapter:"第六卷"},
                {chapter:"第七卷"},
                {chapter:"第八卷"},
                {chapter:"第九卷"},
                {chapter:"第十卷"},
                {chapter:"第十一卷"},
                {chapter:"第十二卷"},
                {chapter:"第十三卷"},
                {chapter:"第十四卷"},
                {chapter:"第十五卷"},
                {chapter:"第十六卷"},
                {chapter:"第十七卷"},
                {chapter:"第十八卷"},
                {chapter:"第十九卷"}
            ],
            imgsrc: "images/novellun2.jpg"},
        {id:"3",title: "期待在地下城邂逅有错吗 第11卷",
            imgcover:"images/novellun3t1.jpg",
            date:"2016-12-17 连载中",
            author:"大森藤野",
            type:"冒险/魔法/后宫",
            click:"点击 6887612",
            Subscribe:"订阅  59995",
            txt:"宫都市欧拉丽——这是一座拥有雄伟地下迷宫（通称「地下城」）的巨大都市。名为未知的兴奋、光辉显赫的荣耀，以及与可爱女孩的罗曼史。",
            newchapter:"外传 剑姬神圣谭7  ",
            allchapter:[{chapter:"第一卷"},
                {chapter:"第二卷"},
                {chapter:"第三卷"},
                {chapter:"第四卷"},
                {chapter:"第五卷"},
                {chapter:"第六卷"},
                {chapter:"第七卷"},
                {chapter:"第八卷"},
                {chapter:"第九卷"},
                {chapter:"第十卷"},
                {chapter:"第十一卷"},
                {chapter:"外传 剑姬神圣谭7 "}
            ],
            imgsrc: "images/novellun3.jpg"},
        {id:"4",title: "魔弹之王与战姬 第15卷",
            imgcover:"images/novellun4t1.jpg",
            date:"2016-11-29 连载中",
            author:"川口士",
            type:"魔法/后宫/战争",
            click:"点击 5431968",
            Subscribe:"订阅  35182",
            txt:"“战姬”——挥舞着由龙授予的超常武器，趋驰于战场之上的美丽少女。在国王的统帅之下，七位战姬分别治理着七块领地，以“吉斯塔托的七战姬”之名深受邻国的畏惧。",
            newchapter:"第十五卷 ",
            allchapter:[{chapter:"第一卷"},
                {chapter:"第二卷"},
                {chapter:"第三卷"},
                {chapter:"第四卷"},
                {chapter:"第五卷"},
                {chapter:"短篇"},
                {chapter:"第六卷"},
                {chapter:"第七卷"},
                {chapter:"第八卷"},
                {chapter:"第九卷"},
                {chapter:"第十卷"},
                {chapter:"漫画附录 anthology "},
                {chapter:"第十一卷"},
                {chapter:"第十二卷"},
                {chapter:"第十三卷"},
                {chapter:"第十四卷"},
                {chapter:"第十五卷"},

            ],
            imgsrc: "images/novellun4.jpg"},
        {id:"5",title: "为美好的世界献上祝福！第十卷",
            imgcover:"images/novellun5t1.jpg",
            date:"2016-12-16 连载中",
            author:"晓なつめ",
            type:"魔法/冒险/搞笑/后宫/异界/穿越",
            click:"点击 3546885",
            Subscribe:"订阅  80313",
            txt:"喜爱游戏的家里蹲少年佐藤和真的人生突然闭幕……但是他的眼前出现自称女神的美少女。转生到异世界的和真就此为了满足食衣住而努力工作！原本只想安稳度日的和真，却因为带去的女神接二连三引发问题",
            newchapter:"第十卷 赌博迷糊大王  ",
            allchapter:[{chapter:"第一卷"},
                {chapter:"第二卷"},
                {chapter:"第三卷"},
                {chapter:"第四卷"},
                {chapter:"番外 为美好的世界献上爆炎！~惠惠的回合~ "},
                {chapter:"第五卷"},
                {chapter:"番外2 为美好的世界献上爆炎！~悠悠的回合~ "},
                {chapter:"第六卷"},
                {chapter:"番外3 为美好的世界献上爆炎！~两人(是最强！)的回合~ "},
                {chapter:"第七卷"},
                {chapter:"第八卷"},
                {chapter:"外传 与面具恶魔进行商谈！ "},
                {chapter:"第九卷"},
                {chapter:"第十卷"},
            ],
            imgsrc: "images/novellun5.jpg"}
    ];
    // 解析参数，查找匹配的
    $scope.product = {};
    angular.forEach($scope.novels,function(product,index){
        if(product.title == $stateParams.title){
            $scope.product = product;
            return;
        }
        console.log("#" + index);
    });
})